### ISSUE TITLE
Some tests fail in bee because the RequestFactory does not populates accepted_renderer

### ISSUE THREAD

**Issue by postfalk** [bkg/django-spillway#27]
```
ERROR: test_query_params (bee.base.tests.test_serializers.TestFieldSelectionMixin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/falk/projects/bee/bee/bee/base/tests/test_serializers.py", line 70, in test_query_params
    item, context={'request': request})
  File "/home/falk/projects/bee/env/local/lib/python2.7/site-packages/spillway/serializers.py", line 33, in __init__
    renderer = self.context['request'].accepted_renderer
AttributeError: 'WSGIRequest' object has no attribute 'accepted_renderer'
```

I already switched to DRF's extension of the Django test framework. 

**Question:** Should I populate this in my tests or could you use a default in spillway if this attribute is not present?

**Comment by bkg** [comment]
Yes, the serializer should definitely work with either Django or DRF request types. Fixed, thanks.
